### ISSUE TITLE
compatibility problem between pop_execution_arg and cosmos.start()

### ISSUE THREAD

**Issue by aurelBZH** [LPM-HMS/COSMOS2#33]
The argument list provided by `pop_execution_arg`seem to be unsuitable with the arguments needed by cosmos.start(). In effect the argument `MAX CORE` don't match with the cosmos.start() method.

**Comment by egafni** [comment]
fixed by #ab501e7

**Comment by aurelBZH** [comment]
I retry to use a variable with the dictionnary provided by pop_execution_arg and I still have the problem. here is my code:    
![code](https://cloud.githubusercontent.com/assets/9987970/13778403/d81f4a54-eab5-11e5-9a6b-97ead86c9e94.png)


the error message say that  cosmos.start got an unexpected keyword argument 'max_cores'
![error_message](https://cloud.githubusercontent.com/assets/9987970/13778274/354f798e-eab5-11e5-8e45-8af2c8047af5.png)

the content of the variable  start_kwargs provided by pop_execution_arg
![start_kwargs](https://cloud.githubusercontent.com/assets/9987970/13778375/ac50c074-eab5-11e5-8535-23820620b5ee.png)

**Comment by egafni** [comment]
Ah - sorry.  max_cores and max_attempts are now parameters of execution.run(), so the pop_execution_arg pattern should have been deprecated.  I've removed it.

See https://github.com/LPM-HMS/Cosmos2/blob/master/examples/variant_calling/recipe.py for an example that passes the arguments correctly
